server:
  port: 10086
  servlet:
    context-path: /java-rag-cloud
spring:
  profiles:
    active: @profiles.active@
  application:
    name: java-rag-cloud
  cloud:
    discovery:
      enabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.kailin.dao.enums.EnumTypeHandler
    cache-enabled: false
  type-enums-package: com.kailin.**.enums
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
