spring:
  datasource:
    druid:
      ragmain:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:33066/java_rag?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
      ragslave:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:33066/java_rag?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
  data:
    redis:
      host: 192.168.21.110
      port: 6379
      database: 7
      auth:
        db: 12
      password: mima123456
  rabbitmq:
    host: 192.168.21.80
    port: 32709
    username: ng_kboss
    password: W58n2iWjPGEVppC7aZ
    #虚拟host 可以不设置,使用server默认host
    virtual-host: ng_kboss
logging:
  level:
    com.kailin: DEBUG
